#!/bin/bash

JUPYTER_PORT=$1
MLFLOW=$2
PARAMS=$3

DOCKERNAME=$(basename $PWD)-jupyter

if [ "$(docker ps -aqf name=$DOCKERNAME)" ]; then
    # if docker exist, then attach to it
    docker attach $DOCKERNAME;
else
    # Starts a docker container in the current folder
    docker run -it -v $PWD:/code/ --name $DOCKERNAME --rm $PARAMS -p $JUPYTER_PORT:8888 -p $MLFLOW:5000 exp
fi;
