#!/bin/bash

#######################
# check folder exists #
#######################
# if not, create folders
[ -d ~/.config ] || { echo "creating .config folder"; mkdir ~/.config; }
[ -d ~/.config/nvim ] || { echo "creating nvim config folder" ; mkdir ~/.config/nvim; }
[ -d ~/.config/nvim/lua ] || { echo "creating nvim/lua config folder" ; mkdir ~/.config/nvim/lua; }
[ -d ~/.config/fish ] || { echo "creating fish config folder" ; mkdir ~/.config/fish; }
[ -d ~/.config/fish/functions ] || { echo "creating fish/functions config folder" ; mkdir ~/.config/fish/functions; }

# macos specific preference
files=(
    "limelight" "skhd" "yabai" "zathura"
    "karabiner" "karabiner/assets"
    "karabiner/assets/complex_modifications"
)
if [[ "$OSTYPE" == "darwin"* ]]; then
    for program in ${files[@]}
    do
        [ -d ~/.config/$program ] || { echo "creating $program config folder"; mkdir ~/.config/$program; }
    done
fi

# linux specific preference
lfiles=(
    "i3" "i3blocks" "rofi"
)
if [[ "$OSTYPE" == "linux"* ]]; then
    for program in ${lfiles[@]}
    do
        [ -d ~/.config/$program ] || { echo "creating $program config folder"; mkdir ~/.config/$program; }
    done
fi


#########################
# create symbolic links #
#########################
files=(
    ".vimrc" ".zshrc" ".tmux.conf" ".gitconfig"
    ".config/nvim/init.vim"
    ".config/nvim/plugin.vim"
    ".config/nvim/keymap.vim"
    ".config/nvim/lua/lualine_theme.lua"
    ".config/nvim/lua/config.lua"
    ".config/fish/config.fish"
    ".config/fish/fish_plugins"
    ".config/fish/functions/fish_prompt.fish"
    ".config/fish/functions/fish_right_prompt.fish"
    );

for file in ${files[@]}
    do
        [ -f ~/$file ] || { echo "creating $file symlink"; ln -s $PWD/$file ~/$file; }
done

# macos specific config files
files=(
    ".config/skhd/skhdrc"
    ".config/yabai/yabairc"
    ".config/limelight/limelightrc"
    ".qutebrowser/config.py"
    ".config/zathura/zathurarc"
    ".config/karabiner/assets/complex_modifications/keymap.json"
)
if [[ "$OSTYPE" == "darwin"* ]]; then
    for file in ${files[@]}
    do
        [ -f ~/$file ] || { echo "creating $file symlink"; ln -s $PWD/$file ~/$file; }
    done
fi

# linux specific config files
lfiles=(
    ".config/i3/config"
    ".config/i3/compton.conf"
    ".config/i3blocks/config"
    ".config/rofi/config.rasi"
)
if [[ "$OSTYPE" == "linux"* ]]; then
    for file in ${lfiles[@]}
    do
        [ -f ~/$file ] || { echo "creating $file symlink"; ln -s $PWD/$file ~/$file; }
    done
fi

####################
# workplace script #
####################
files=("nb_clean" "tmux_setup")
for file in ${files[@]}
do
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        [ -f /usr/local/bin/$file ] || { echo "transfer $file"; sudo ln -s $PWD/$file /usr/local/bin/$file; }
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        [ -f /usr/local/bin/$file ] || { echo "transfer $file"; ln -s $PWD/$file /usr/local/bin/$file; }
    fi
done

echo "Done with config"
