#!/bin/bash

# Check if machine has internet access beyond pypi #
INTERNET=$1
# read -p "Good day, do we have internet access beyond pypi? - y/n " INTERNET

# check if user want to setup workplace script
WORKPLACE=$2
# read -p "Do you want to set up workplace script? - y/n " WORKPLACE

###################
# Helper function #
###################
custom_ln () {
    # loops through the inputs to create symbolic links
    # if file exist, then do nothing
    for file in "$@"
    do
        path=$HOME/$file
        if [ -e $path ]; then
            echo "$file exist"
        else
            echo "creating $file symlink";
            ln -s $PWD/$file $HOME/$file
        fi
    done
}

#######################
# check folder exists #
#######################
echo "======================="
echo "creating symbolic links"
echo "======================="
[ -d $HOME/.config ] || { echo "creating .config folder"; mkdir $HOME/.config; }

#########################
# create symbolic links #
#########################
custom_ln ".vimrc" ".tmux.conf" ".gitconfig"
custom_ln ".config/nvim" ".config/fish"

# fish shell special
config_fish=$HOME/.config/fish/config.fish
if [ ! -e $config_fish ]; then
    echo "add in fish config"
    echo "fish_vi_key_bindings" > $config_fish
fi

# only if access beyond pypi is available
if [[ $INTERNET =~ ^[Yy].* ]]; then
    echo "====================================="
    echo "set up files for internet only config"
    echo "====================================="

    custom_ln ".qutebrowser" ".config/zathura"

    # macos specific config files
    if [[ "$OSTYPE" == "darwin"* ]]; then
        mfolders=(
            ".config/skhd"
            ".config/yabai"
            ".config/limelight"
            ".config/karabiner"
        )
        custom_ln "${mfolders[@]}";
    fi

    # linux specific config files
    if [[ "$OSTYPE" == "linux"* ]]; then
        lfolders=(
            ".config/i3"
            ".config/i3blocks"
            ".config/rofi"
        )
        custom_ln "${lfolders[@]}";
    fi

    # ensure check.lua is yes
    echo "internet = 1" > $HOME/.config/nvim/lua/check.lua

else
    # change the check.lua to no
    echo "internet = 0" > $HOME/.config/nvim/lua/check.lua
fi

####################
# workplace script #
####################
if [[ $WORKPLACE =~ ^[Yy].* ]]; then
    echo "======================="
    echo "Set up workplace script"
    echo "======================="

    files=("nb_clean" "tmux_setup")
    for file in ${files[@]}
    do
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
            [ -f /usr/local/bin/$file ] || { echo "transfer $file"; sudo ln -s $PWD/$file /usr/local/bin/$file; }
        elif [[ "$OSTYPE" == "darwin"* ]]; then
            [ -f /usr/local/bin/$file ] || { echo "transfer $file"; sudo ln -s $PWD/$file /usr/local/bin/$file; }
        fi
    done
fi

echo "================"
echo "Done with config"
echo "================"
