#!/bin/bash

#######################
# check folder exists #
#######################
# if not, create folders
[ -d ~/.config ] || { echo "creating .config folder"; mkdir ~/.config; }
[ -d ~/.config/nvim ] || { echo "creating nvim config folder" ; mkdir ~/.config/nvim; }
[ -d ~/.config/nvim/lua ] || { echo "creating nvim/lua config folder" ; mkdir ~/.config/nvim/lua; }

# macos specific preference
if [[ "$OSTYPE" == "darwin"* ]]; then
    for program in "limelight" "skhd" "yabai"
    do
        [ -d ~/.config/$program ] || { echo "creating $program config folder"; mkdir ~/.config/$program; }
    done
fi


#########################
# create symbolic links #
#########################
files=(".vimrc" ".zshrc" ".tmux.conf" ".gitconfig" ".config/nvim/init.vim" ".config/nvim/lua/lualine_theme.lua");

for file in ${files[@]}
    do
        [ -f ~/$file ] || { echo "creating $file symlink"; ln -s $PWD/$file ~/$file; }
done

# macos specific config files
if [[ "$OSTYPE" == "darwin"* ]]; then
    for file in "skhd/skhdrc" "yabai/yabairc" "limelight/limelightrc"
    do
        [ -f ~/.config/$file ] || { echo "creating $file symlink"; ln -s $PWD/.config/$file ~/.config/$file; }
    done
fi


##########################################
# optional workplace script require sudo #
##########################################
read -p "Copy script to bin? " command;
case $command in
    [Yy]es )
        for file in "nb_clean" "tmux_setup"
        do
            [ -f /usr/local/bin/$file ] || { echo "transfer $file"; sudo ln -s $PWD/$file /usr/local/bin/$file; }
        done;;
    * )
        echo "ok no script is transferred";;
esac

echo "Done with config"
