#!/bin/bash

# this script will remove the current config files
# useful for re-installing all the config files

files=(
    ".vimrc" ".tmux.conf" ".gitconfig"
    ".qutebrowser"
    ".config/nvim"
    ".config/fish"
    ".qutebrowser"
    ".config/zathura"
    ".config/skhd"
    ".config/yabai"
    ".config/limelight"
    ".config/karabiner"
    ".config/i3"
    ".config/i3blocks"
    ".config/rofi"
    );

for file in ${files[@]}
    do
        [ -e $HOME/$file ] && { echo "deleting $file"; rm $HOME/$file; }
done

# clean the workspace files

files=("nb_clean" "tmux_setup")
for file in ${files[@]}
do
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        [ -f /usr/local/bin/$file ] && { echo "deleting $file"; sudo rm /usr/local/bin/$file; }
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        [ -f /usr/local/bin/$file ] && { echo "deleting $file"; sudo rm /usr/local/bin/$file; }
    fi
done
