#!/bin/bash

# this script will remove the current config files
# useful for re-installing all the config files

files=(
    ".vimrc" ".zshrc" ".tmux.conf" ".gitconfig"
    ".config/nvim/init.vim"
    ".config/nvim/plugin.vim"
    ".config/nvim/keymap.vim"
    ".config/nvim/check.vim"
    ".config/nvim/lua/lualine_theme.lua"
    ".config/nvim/lua/config.lua"
    ".config/fish/config.fish"
    ".config/fish/fish_plugins"
    ".config/fish/functions/fish_prompt.fish"
    ".config/fish/functions/fish_right_prompt.fish"
    ".qutebrowser/config.py"
    ".config/zathura/zathurarc"
    );

for file in ${files[@]}
    do
        [ -f ~/$file ] && { echo "deleting $file"; rm ~/$file; }
done

# macos specific config files
files=(
    ".config/skhd/skhdrc"
    ".config/yabai/yabairc"
    ".config/limelight/limelightrc"
    ".config/karabiner/assets/complex_modifications/keymap.json"
)
if [[ "$OSTYPE" == "darwin"* ]]; then
    for file in ${files[@]}
    do
        [ -f ~/$file ] && { echo "deleting $file"; rm ~/$file; }
    done
fi

# linux specific config files
lfiles=(
    ".config/i3/config"
    ".config/i3/compton.conf"
    ".config/i3blocks/config"
    ".config/rofi/config.rasi"
)
if [[ "$OSTYPE" == "linux"* ]]; then
    for file in ${lfiles[@]}
    do
        [ -f ~/$file ] && { echo "deleting $file"; rm ~/$file; }
    done
fi

files=("nb_clean" "tmux_setup")
for file in ${files[@]}
do
    if [[ "$OSTYPE" == "linux-gnu"* ]]; then
        [ -f /usr/local/bin/$file ] && { echo "deleting $file"; sudo rm /usr/local/bin/$file; }
    elif [[ "$OSTYPE" == "darwin"* ]]; then
        [ -f /usr/local/bin/$file ] && { echo "deleting $file"; sudo rm /usr/local/bin/$file; }
    fi
done
